<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Fill-Tables-with-data-from-jsons" data-toc-modified-id="Fill-Tables-with-data-from-jsons-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Fill Tables with data from jsons</a></span><ul class="toc-item"><li><span><a href="#regattas" data-toc-modified-id="regattas-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>regattas</a></span></li><li><span><a href="#races" data-toc-modified-id="races-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>races</a></span></li><li><span><a href="#competitors" data-toc-modified-id="competitors-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>competitors</a></span></li><li><span><a href="#windsources-&amp;-wind" data-toc-modified-id="windsources-&amp;-wind-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>windsources &amp; wind</a></span></li><li><span><a href="#legs" data-toc-modified-id="legs-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>legs</a></span></li><li><span><a href="#race_comp" data-toc-modified-id="race_comp-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>race_comp</a></span></li><li><span><a href="#comp_leg" data-toc-modified-id="comp_leg-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>comp_leg</a></span></li><li><span><a href="#positions" data-toc-modified-id="positions-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>positions</a></span></li><li><span><a href="#courses" data-toc-modified-id="courses-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>courses</a></span></li><li><span><a href="#marks" data-toc-modified-id="marks-1.10"><span class="toc-item-num">1.10&nbsp;&nbsp;</span>marks</a></span></li><li><span><a href="#marks_positions" data-toc-modified-id="marks_positions-1.11"><span class="toc-item-num">1.11&nbsp;&nbsp;</span>marks_positions</a></span></li><li><span><a href="#Extra-functions-in-case-something-went-wrong-for-a-few-entries" data-toc-modified-id="Extra-functions-in-case-something-went-wrong-for-a-few-entries-1.12"><span class="toc-item-num">1.12&nbsp;&nbsp;</span>Extra functions in case something went wrong for a few entries</a></span></li></ul></li><li><span><a href="#Fill-columns-with-extra-information-to-complete-database" data-toc-modified-id="Fill-columns-with-extra-information-to-complete-database-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Fill columns with extra information to complete database</a></span><ul class="toc-item"><li><span><a href="#Update-final-rank-in-race_comp" data-toc-modified-id="Update-final-rank-in-race_comp-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Update final rank in race_comp</a></span></li><li><span><a href="#Get-chosen-side-of-competitors-for-leg-1" data-toc-modified-id="Get-chosen-side-of-competitors-for-leg-1-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Get chosen side of competitors for leg 1</a></span></li><li><span><a href="#Determining-Course-Area" data-toc-modified-id="Determining-Course-Area-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Determining Course Area</a></span></li><li><span><a href="#Number-of-competitors-per-race-and-their-relative-rank" data-toc-modified-id="Number-of-competitors-per-race-and-their-relative-rank-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Number of competitors per race and their relative rank</a></span></li><li><span><a href="#Categorize-Sailing-Style-per-Race" data-toc-modified-id="Categorize-Sailing-Style-per-Race-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Categorize Sailing Style per Race</a></span></li><li><span><a href="#Positions-Start-Line" data-toc-modified-id="Positions-Start-Line-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Positions Start Line</a></span></li><li><span><a href="#positions_view" data-toc-modified-id="positions_view-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>positions_view</a></span></li><li><span><a href="#Calculate-Correlations" data-toc-modified-id="Calculate-Correlations-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>Calculate Correlations</a></span></li></ul></li><li><span><a href="#Extra" data-toc-modified-id="Extra-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Extra</a></span><ul class="toc-item"><li><span><a href="#Usefull-other-queries" data-toc-modified-id="Usefull-other-queries-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Usefull other queries</a></span></li><li><span><a href="#move-all-data-to-right-indexed" data-toc-modified-id="move-all-data-to-right-indexed-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>move all data to right indexed</a></span></li></ul></li></ul></div>

# Fill Tables with data from jsons

In [1]:
###############################
## Tabellen vullen
###############################
import os, sys, inspect, json
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.append(parentdir)
from lib.Utilities.globalVar import *
import lib.TransformData.combineData as combd
import Download.download as download
from Utilities.converter import *

# currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
# parentdir = os.path.dirname(currentdir)
# sys.path.append(parentdir)
from sqlalchemy import *
from sqlalchemy.exc import IntegrityError, InternalError
from sqlalchemy.types import BINARY, VARCHAR
import pandas as pd
import numpy as np
from math import *
import urllib, json, requests


import pyodbc


from sqlalchemy.types import TypeDecorator, CHAR
from sqlalchemy.dialects.postgresql import UUID
import uuid

In [7]:

server = 'sic-match-analysis.database.windows.net'
database = 'match-analysis'
username = 'sic-admin'
password = 'ZeilenIsLeuk!'
driver= '{ODBC Driver 17 for SQL Server}'
connection_str = 'DRIVER='+driver+';SERVER='+server+';PORT=1433;DATABASE='+database+';UID='+username+';PWD='+ password


cnxn = pyodbc.connect(connection_str)
cursor = cnxn.cursor()

quoted = urllib.parse.quote_plus(connection_str)
engine = create_engine('mssql+pyodbc:///?odbc_connect={}'.format(quoted))

from sqlalchemy import event

@event.listens_for(engine, 'before_cursor_execute')
def receive_before_cursor_execute(conn, cursor, statement, params, context, executemany):
    if executemany:
        cursor.fast_executemany = True
        cursor.commit()

In [3]:
## Lukt niet om met bulk insert vanaf locale dir bestanden up te loaden :( dus moet via pandas to_sql
# cursor.execute("""
# BULK INSERT regattas
# FROM '\\usman-ess/Folder Redirection/Nerine/Documents/TU_Delft/2_Master/3_Stage/2_Code/SAPDataAnalysis/data/raw/tokyo2019'
# """)
event  = [{'name' :  'hwcs2020-round1', 'AllRegattas': True, 'regattaNameContaining': '', 'raceNameContaining': ''}
         ,{'name' : 'www', 'AllRegattas' : False, 'regattaNameContaining': 'Enoshima', 'raceNameContaining': ''}
         ,{'name' :  'tokyo2019', 'AllRegattas': True, 'regattaNameContaining': '', 'raceNameContaining': ''}]
events = [{'name' :  'tokyo2019', 'AllRegattas': True, 'regattaNameContaining': '', 'raceNameContaining': ''}]
eventSelection = events
parentdir
cd = combd.combineData()

## regattas

In [4]:
## TABLE 1 regattas
for serv in eventSelection:
    filepath = parentdir + '/' +  outdirbase + serv['name'] + '/regattas'
    with open(filepath + '.json') as json_file:
        print('file extracted: ', filepath)
        data = json.load(json_file)
        
    data2 = getData()
    cd = combd.combineData(serv)
    df = cd.transformJsonToPD(data, 'regattas')
    serv['regattas'] = df
    try:
        df.to_sql('regattas', con = engine, index = False, if_exists = 'append')
        print('Succesfully added regattas of {} to the database'.format(serv['name']))
    except IntegrityError as e:
        print('Could not add regattas of {} to the database because of IntegrityError: {}'.format(serv['name'], e))

FileNotFoundError: [Errno 2] No such file or directory: 'X:\\TU_Delft\\2_Master\\3_Stage\\2_Code\\SAPDataAnalysis\\lib//data/raw/tokyo2019/regattas.json'

## races

In [ ]:
# TABLE 2 races columns; 
# regatta
# race
# raceShort
# raceId
# maxWindSpd_kts
# minWindSpd_kts
# avgWindDir_deg
# firstlegbearing_deg

# coming from races, windsummary and firstlegbearing
filenames = ['races', 'windsummary', 'firstlegbearing']

for serv in eventSelection:
    for indx, regatta in serv['regattas'].iterrows():
        regName = regatta.regatta
        directory_regatta = parentdir + '/' + outdirbase + webAddressToFilename(serv['name']) + \
                            webAddressToFilename(regattaLoc(regName))
        filepath = directory_regatta + 'races.json'
        with open(filepath) as json_file:
            print('file extracted: ', filepath)
            data = json.load(json_file)
        dic_data = {'regatta': regName, 'data': data}
        races = cd.transformJsonToPD(dic_data, 'races')
        
        
        filepath = directory_regatta + 'windsummary.json'
        with open(filepath) as json_file:
            print('file extracted: ', filepath)
            data = json.load(json_file)
        dic_data = {'regatta': regName, 'data': data}
        windsummary = cd.transformJsonToPD(dic_data, 'windsummary').set_index(['regatta', 'raceShort'])   
        
        flb = []
        for index, race in races.iterrows():
            directory_race = parentdir + '/' + outdirbase +serv['name'] + \
                             webAddressToFilename(raceLoc(regName, race['race']))
            filepath = directory_race + 'firstlegbearing.json'
            with open(filepath) as json_file:
#                 print('file extracted: ', filepath)
                data = json.load(json_file)
            dic_data = {'regatta': regName, 'race': race['race'], 'data': data}
            firstlegbearing = cd.transformJsonToPD(dic_data, 'firstlegbearing') 
            flb.append(firstlegbearing)
        flb = pd.concat(flb).set_index(['regatta', 'race'])
        
    
        races = races.set_index(['regatta','raceShort'])
        result = pd.concat([races, windsummary], axis=1, join='outer').reset_index().set_index(['regatta', 'race'])
        result = pd.concat([result, flb], axis=1, join='outer').reset_index()
        
#         print('with as result', result)
        
        try:
            result.to_sql('races', con = engine, index = False, if_exists = 'append')
            print('Succesfully added races of {} {} to the database'.format(regName, race['race']))
        except IntegrityError as e:
            print('Could not add races of {} {} to the database because of IntegrityError: {}'.format(regName,race['race'],e))

In [ ]:
## add begin and end time to races
for serv in eventSelection:
    for indx, regatta in serv['regattas'].iterrows():
        regName = regatta.regatta
        print(regName)
        dir_races =  parentdir + '/' + outdirbase + webAddressToFilename(serv['name']) + \
                    webAddressToFilename(regattaLoc(regName)) + '/races/'
        for race in os.listdir(dir_races):
            filepath = dir_races + race + "/times.json"
            with open(filepath) as json_file:
#                     print('file extracted: ', filepath)
                data = json.load(json_file)
            dic_data = {'regatta': regName, 'race': filenameToWebAddress(race), 'data': data}
            df = cd.transformJsonToPD(dic_data, 'times')#.set_index(['regatta', 'comp_name']) 

            times = [df['startOfRace-ms'].values[0],df['endOfRace-ms'].values[0]]
            if times[0] is None:
                continue
#             #update
            cursor.execute("""
                UPDATE races
                SET    races.[startOfRace-ms] = {}
                       ,races.[endOfRace-ms] = {}
                WHERE
                regatta = '{}'
                  and race = '{}'
                  """.format(df['startOfRace-ms'].values[0],df['endOfRace-ms'].values[0] 
                             , regName , filenameToWebAddress(race))
                          )
            cursor.commit()

## competitors

In [ ]:
## TABLE 3 Competitors
for serv in eventSelection:
    d = download.download(server = serv['name'], regattasContaining = serv['regattaNameContaining'],\
    racesContaining = serv['raceNameContaining'])
    for indx, regatta in serv['regattas'].iterrows():
        regName = regatta.regatta
        
        directory_regatta =  parentdir + '/' + outdirbase + webAddressToFilename(serv['name']) +\
                                webAddressToFilename(regattaLoc(regName))
        filepath = directory_regatta + 'entries.json'
        with open(filepath) as json_file:
#             print('file extracted: ', filepath)
            data = json.load(json_file)
        dic_data = {'regatta': regName, 'data': data}
        competitors = cd.transformJsonToPD(dic_data, 'entries').set_index(['regatta', 
                                                                          'comp_name'])
#         print(competitors.head())


        dir_datamining =  parentdir + '/' + outdirbase + webAddressToFilename(serv['name']) + \
                        webAddressToFilename(regattaLoc(regName)) + '/datamining/'
        datamining_reg = []
        for root, dirs, files in os.walk(dir_datamining, topdown=True):
            for file in files:
                fname = os.path.splitext(file)[0]
                if file.endswith(".json"):
                    with open(root + file) as json_file:
#                         print('file extracted: ', root + file)
                        data = json.load(json_file)
                    dic_data = {'regatta': regName, 'data': data}
                    df = cd.transformJsonToPD(dic_data, fname).set_index(['regatta', 'comp_name']) 
                    datamining_reg.append(df)
#                   print('df: ',df.head())

        datamining_reg = pd.concat(datamining_reg, axis = 1, join = 'outer')
            
        result = pd.merge(datamining_reg.reset_index(), competitors.reset_index(), how='left')
#         print('comp', result.head())
        result.to_sql('competitors', con = engine, index = False, if_exists = 'append')
        print('Succesfully uploaded competitors from {} to sql server'.format(regName))

## windsources & wind

In [ ]:
sql = """SELECT  [regatta]
      ,[race]
  FROM [dbo].[race_comp] as rc
  group by regatta, race
  Having max(pos_startline_rel) is Null
"""


eventSelection = pd.read_sql(sql, con= engine)
eventSelection

sql = """SELECT  windsources.regatta, windsources.race, avg(stl_bearing_diff_wind)  from races INNER JOIN 
windsources on windsources.regatta = races.regatta and windsources.race = races.race
where stl_bearing_diff_wind is not null
group by windsources.regatta, windsources.race
having MAX(CAST(rc as INT)) is null
"""


eventSelection = pd.read_sql(sql, con= engine)
eventSelection

In [ ]:
## Table 4 wind

for indx, row in eventSelection.iterrows():    
    regName = row.regatta
    raceName = row.race

# for serv in eventSelection:
#     for indx, regatta in serv['regattas'].iterrows():
#         regName = regatta.regatta
#         dir_races =  parentdir + '/' + outdirbase + webAddressToFilename(serv['name']) + \
#                         webAddressToFilename(regattaLoc(regName)) + '/races/'
        
#         for race in os.listdir(dir_races):
#             raceName = filenameToWebAddress(race)
    ## quick check whether there are already windsources loaded
    print('Get first pos windsources', end = '\r')
    sql = """ SELECT * FROM {}
            WHERE regatta = '{}'
            and race = '{}'
          """.format('windsources', regName, raceName)
    check = pd.read_sql(sql, con = engine) ## already a positions for this race ?   
    if check.empty:
#                     print('\tAlready positions found in wind for \t{} \t{} \t{}'.format(regName, raceName, ws.typeName, ws.id))
        print('Fetch windsources data', end = '\r')        
        url_ws = windUrl(regName, raceName)
        data = requests.get(url_ws, timeout = 100)

        if data.status_code == 404:
            print('No windsources available for {} {}'.format(regName, raceName))
            continue
        data = data.json()
        print('Transform windsources data', end = '\r')        
        df = cd.transformJsonToPD(data, 'windsources')
        toSql(df,'windsources', engine, regName, raceName)
    else:
        df = check

    for idx, ws in df.iterrows():
        ## quick check whether there are already entries
        if ws.typeName != "EXPEDITION":
            continue
 
        print('Get first pos wind        ', end = '\r')
        sql = """ SELECT TOP (1) * FROM {}
                WHERE regatta = '{}'
                and race = '{}'
                and windSource = 'EXPEDITION'
                and windSource_id = '{}'
              """.format('wind', regName, raceName,  ws.id)
        check = pd.read_sql(sql, con = engine) ## already a positions for this race ?   
        if not check.empty:
#                     print('\tAlready positions found in wind for \t{} \t{} \t{}'.format(regName, raceName, ws.typeName, ws.id))
            continue
        print('load data from url', end = '\r')
        url_wind = windUrl(regName, raceName, windSource = ws.typeName, windSourceId = ws.id)
        data = requests.get(url_wind, timeout = 100)
        if data.status_code == 400:
            print('\tNo wind available for {} {} {}'.format(regName, raceName, ws.typeName))
            continue
        data = data.json()
        df = cd.transformJsonToPD(data, 'wind')
        if df.empty:
            print('\tNo wind available for {} {} {} {}'.format(regName, raceName, ws.typeName, ws.id))
            continue            
        df.windSource = df.windSource.apply(lambda x: ws.typeName)
        df['windSource_id'] = df.windSource.apply(lambda x: ws.id)
        print('Upload wind data to sql server', end = '\r')
        print(url_wind)
        e = toSql(df, 'wind', engine, regName, raceName + ws.typeName + ws.id)

In [ ]:
url_wind

## legs

In [ ]:
## TABLE 5 legs
# [regatta]
# ,[race]
# ,[leg_nr]
# ,[fromWaypointId]
# ,[toWaypointId]
# ,[to]
# ,[from]
# ,[upOrDownwindLeg]
# ,[leg_nr_from_finish]
# ,[distance]


for serv in eventSelection:
    for indx, regatta in serv['regattas'].iterrows():
        regName = regatta.regatta
        dir_races =  parentdir + '/' + outdirbase + webAddressToFilename(serv['name']) + \
                        webAddressToFilename(regattaLoc(regName)) + '/races/'
        for race in os.listdir(dir_races):
            filepath = dir_races + race + "/competitors/legs.json"
            if filepath.endswith(".json"):
                with open(filepath) as json_file:
#                     print('file extracted: ', filepath)
                    data = json.load(json_file)
                dic_data = {'regatta': regName, 'race': filenameToWebAddress(race), 'data': data}
                df = cd.transformJsonToPD(dic_data, 'legs') 
#                 print('df: ',df.head())

                try:
                    df.to_sql('legs', con = engine, index = False, if_exists = 'append')
                    print('Succesfully uploaded wind for regatta: \t{}, race: \t{}'.format(regName, race))
                except IntegrityError as e:
                    print('WARNING: Failed to upload to sql: '+ str(e))

## race_comp

### temorarily delete entries in comp_leg, because I accidentally deleted to many similar rows

cursor.execute("""
DELETE FROM legs;
""")

In [ ]:
### TABLE 6
## This code create all entries in race_comp. We do this by checking that the nr_competitors in 
## the races table is still NULL because we did not update that yet.
## We will later add rank, based on comp_leg
cursor.execute("""
INSERT INTO race_comp(regatta, race, comp_id)
SELECT races.regatta, races.race, competitors.comp_id FROM races, competitors
WHERE races.regatta = competitors.regatta
 and races.nr_competitors IS NULL
""")

## comp_leg

In [ ]:
## TABLE 7 comp_leg
# [regatta]
# ,[race]
# ,[leg_nr]
# ,[comp_id]
# ,[competitor_distanceTraveled-m]
# ,[competitor_averageSOG-kts]
# ,[competitor_tacks]
# ,[competitor_jibes]
# ,[competitor_penaltyCircles]
# ,[competitor_rank]
# ,[competitor_gapToLeader-s]
# ,[competitor_gapToLeader-m]
# ,[competitor_started]
# ,[competitor_finished]




for serv in eventSelection:
    
    for indx, regatta in serv['regattas'].iterrows():
        regName = regatta.regatta
        dir_races =  parentdir + '/' + outdirbase + webAddressToFilename(serv['name']) + \
                    webAddressToFilename(regattaLoc(regName)) + '/races/'
        for race in os.listdir(dir_races):
            filepath = dir_races + race + "/competitors/legs.json"
            if filepath.endswith(".json"):
                with open(filepath) as json_file:
#                     print('file extracted: ', filepath)
                    data = json.load(json_file)
                dic_data = {'regatta': regName, 'race': filenameToWebAddress(race), 'data': data}
                df = cd.transformJsonToPD(dic_data, 'comp_leg') 
#                 print('df: ',df.head())



                try:
                    df.to_sql('comp_leg', con = engine, index = False, if_exists = 'append')
                    print('Succesfully uploaded wind for regatta: \t{}, race: \t{}'.format(regName, race))
                except IntegrityError as e:
                    print('Could not add races of {} {} to the database because of IntegrityError: {}'.format(regName,
                                                                                                              race,
                                                                                                              e))

In [ ]:
### Markpassings, to update legnr_columnn in positions

cursor.execute("""
DROP TABLE temp_markpassings
CREATE TABLE temp_markpassings
(regatta varchar(50) NOT NULL,
race varchar(50) NOT NULL,
comp_id binary(16) NOT NULL,
leg_nr int NOT NULL,
begin_leg_ms bigint NULL,
end_leg_ms bigint NULL

)

CREATE UNIQUE INDEX idx ON temp_markpassings (regatta, race, leg_nr, comp_id);
CREATE CLUSTERED INDEX idx_2 ON temp_markpassings (regatta, race, comp_id);

""")

cursor.execute("""
ALTER TABLE temp_markpassings
ADD CONSTRAINT fk_temp_markpassings_comp_leg FOREIGN KEY (regatta, race, leg_nr, comp_id)
      REFERENCES comp_leg (regatta, race, leg_nr, comp_id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
""")

In [ ]:
#### TEMPORARY TABLE MARKPASSINGS
for serv in eventSelection:
    for indx, regatta in serv['regattas'].iterrows():
        regName = regatta.regatta
        dir_races =  parentdir + '/' + outdirbase + webAddressToFilename(serv['name']) +\
                    webAddressToFilename(regattaLoc(regName)) + '/races/'
        for race in os.listdir(dir_races):
            filepath = dir_races + race + "/markpassings.json"
            with open(filepath) as json_file:
#                 print('file extracted: ', filepath)
                data = json.load(json_file)
            dic_data = {'regatta': regName, 'race': filenameToWebAddress(race), 'data': data}
            df = cd.transformJsonToPD(dic_data, 'markpassings') 
            if not df.empty:
#                 print(df.leg_nr.unique())
                try:                
                    df.to_sql('temp_markpassings', con = engine, index = False, if_exists = 'append')

                    print('Succesfully added markpassings of \t{} \t{} \tto the database'.format(regName, race))
                except IntegrityError as e:
                    print('Could not add markpassings of \t{} \t{} \tto the database because of IntegrityError:'.format(regName,race))

                    
                    else:
                print('Warning: markpassings for \t{} \t{} \t was empty'.format(regName, race))

## positions

In [ ]:

sql = """
SELECT * from legs 
where pos_startline_abs_x IS NULL and
correlation_side is not null
and leg_nr = 1

"""


eventSelection = pd.read_sql(sql, con= engine)
eventSelection

In [ ]:
## TABLE 8 positions

for ids, row in eventSelection.iterrows():
    regName = row.regatta
    raceName = row.race
    
    print('Get first positions\t\t\t', end = '\r')
    sql = """ SELECT * FROM {}
            WHERE regatta = '{}'
            and race = '{}'
          """.format('positions', regName, raceName)
    check = pd.read_sql(sql, con = engine) ## already a positions for this race ?   
    if not check.empty:
        print('Already positions found in db for \t{} \t{}'.format(regName, raceName))
        continue

    print('get markpassings\t\t\t', end="\r")
    sql = """ SELECT * FROM temp_markpassings
            WHERE regatta = '{}'
            and race = '{}'
            """.format(regName, raceName)
    mps = pd.read_sql(sql, con = engine) ## markpassings for this race
    if mps.empty:
        print('No markpassings where found for\t{} \t{}'.format(regName, raceName))
        continue        
        
    print('Fetch positions data\t\t\t', end = '\r')        
    url_ws = dataUrl(regName, raceName, 'positions_comp')
    data = requests.get(url_ws, timeout = 100)

    if data.status_code == 404:
        print('No positions available for {} {}'.format(regName, raceName))
        continue
    data = data.json()
    
    dic_data = {'regatta': regName, 'race': raceName, 'data': data}
    print('Transform positions data\t\t\t', end = '\r')        
    df = cd.transformJsonToPD(dic_data, 'competitor_positions')

    print('determine leg numbers\t\t\t', end="\r")
    for idx, comp_leg in mps.iterrows():
        df.loc[(df.comp_id == comp_leg.comp_id) & (df['timepoint_ms'] > comp_leg.begin_leg_ms)
               & (df['timepoint_ms'] < comp_leg.end_leg_ms),'leg_nr'] = comp_leg.leg_nr
    df = df.dropna(subset=['leg_nr'])
    
    toSql(df,'positions', engine, regName, raceName)

In [ ]:
# quick import when a positions file was truncated 

import urllib, json, requests

servName = 'hwcs2020-round1'
regName = 'HWCS 2020 Round 1 - Finn'
raceName = 'R6 (FINN)'

url = 'https://www.sapsailing.com/sailingserver/api/v1/regattas/{}/races/{}/competitors/positions'.format(regName,
                                                                                                          raceName)
filename = '{}/data/raw/{}/regattas/{}/races/{}/competitors/positions.json'.format(parentdir, servName, regName, raceName)
try:
    r = requests.get(url).json()
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    print(filename)
except ValueError:
    print("Oops! ", loc , " did not contain the right data for the races")

with open(filename, 'w+') as outfile:
    print('Created new file:', filename)
    json.dump(r, outfile)

## courses

In [ ]:
## Table 9 courses


for serv in eventSelection:
    for indx, regatta in serv['regattas'].iterrows():
        regName = regatta.regatta
        dir_races =  parentdir + '/' + outdirbase + webAddressToFilename(serv['name']) + \
                        webAddressToFilename(regattaLoc(regName)) + '/races/'
        for race in os.listdir(dir_races):
            filepath = dir_races + race + "/course.json"
            with open(filepath) as json_file:
#               print('file extracted: ', filepath)
                data = json.load(json_file)
            dic_data = {'regatta': regName, 'race': filenameToWebAddress(race), 'data': data}
            df = cd.transformJsonToPD(dic_data, 'course') 
#             print('df: ', df.head())

            try:
                df.to_sql('courses', con = engine, index = False, if_exists = 'append')
                print('Succesfully uploaded courses for regatta: \t{}, race: \t{}'.format(regName, race))
            except IntegrityError as e:
                df
                print('WARNING: Failed to upload to sql: '+ str(e))

## marks

In [ ]:
## Table 10 marks

for serv in eventSelection:
    for indx, regatta in serv['regattas'].iterrows():
        regName = regatta.regatta
        dir_races =  parentdir + '/' + outdirbase + webAddressToFilename(serv['name']) + \
                        webAddressToFilename(regattaLoc(regName)) + '/races/'
        for race in os.listdir(dir_races):
            
            print('Get first marks', end = '\r')
            sql = """ SELECT TOP (1) * FROM marks
                    WHERE regatta = '{}'
                    and race = '{}'
                  """.format(filenameToWebAddress(regName), filenameToWebAddress(race))
            pos = pd.read_sql(sql, con = engine) ## already a positions for this race ?   
            if not pos.empty:
                print('Already positions found in db for \t{} \t{}'.format(regName, race))
                continue

            filepath = dir_races + race + "/marks/positions.json"
            with open(filepath) as json_file:
#               print('file extracted: ', filepath)
                data = json.load(json_file)
            dic_data = {'regatta': regName, 'race': filenameToWebAddress(race), 'data': data}
            df = cd.transformJsonToPD(dic_data, 'marks') 
#             print('df: ', df)

            try:
                df.to_sql('marks', con = engine, index = False, if_exists = 'append')
                print('Succesfully uploaded marks for regatta: \t{}, race: \t{}'.format(regName, race))
            except IntegrityError as e:
                print(df.head())
                print('WARNING: Failed to upload to sql: \t{}, race: \t{}, {}'.format(regName, race, e))

## marks_positions

In [ ]:
## Table 9 marks_positions

for serv in eventSelection:
    for indx, regatta in serv['regattas'].iterrows():
        regName = regatta.regatta
        dir_races =  parentdir + '/' + outdirbase + webAddressToFilename(serv['name']) + \
                        webAddressToFilename(regattaLoc(regName)) + '/races/'
        for race in os.listdir(dir_races):
            
            print('Get first pos', end = '\r')
            sql = """ SELECT TOP (1) * FROM marks_positions
                    WHERE regatta = '{}'
                    and race = '{}'
                  """.format(filenameToWebAddress(regName), filenameToWebAddress(race))
            pos = pd.read_sql(sql, con = engine) ## already a positions for this race ?   
            if not pos.empty:
                print('Already positions found in db for \t{} \t{}'.format(regName, race))
                continue
                
            filepath = dir_races + race + "/marks/positions.json"
            with open(filepath) as json_file:
                data = json.load(json_file)
            dic_data = {'regatta': regName, 'race': filenameToWebAddress(race), 'data': data}
            df = cd.transformJsonToPD(dic_data, 'marks_positions') 

#             print('df: ', df)
            print('uploading to sql', end = '\r')
            try:
                df.to_sql('marks_positions', con = engine, index = False, if_exists = 'append')
                print('Succesfully uploaded marks for regatta: \t{}, race: \t{}'.format(regName, race))
            except IntegrityError as e:
                print('WARNING: Failed to upload to sql: \t{}, race: \t{}'.format(regName, race))

## Extra functions in case something went wrong for a few entries

In [ ]:
### Extra functions to manually add tracks of seperate competitors
## in the previous cell tracks have been added per race, but for some reason it went wrong in some cases

def uploadPositions(regName, race, comp_id):
    dir_races =  parentdir + '/' + outdirbase + webAddressToFilename(serv['name']) + \
                    webAddressToFilename(regattaLoc(regName)) + '/races/'
    filepath = dir_races + webAddressToFilename(race) + "/competitors/positions.json"
    sql = """ SELECT * FROM temp_markpassings
            WHERE regatta = '{}'
            and race = '{}'
            and comp_id = {}
            """.format(regName, race, comp_id)
    mps = pd.read_sql(sql, con = engine) ## markpassings for this race
    
    if mps.empty:
        print('No markpassings found, try to download them again')
    
    with open(filepath) as json_file:
#                     print('file extracted: ', filepath)
        data = json.load(json_file)
    dic_data = {'regatta': regName, 'race': filenameToWebAddress(race), 'data': data}

    print('transform to pd', end="\r")
    df = cd.transformJsonToPD(dic_data, 'competitor_positions') 

    print('determine leg numbers', end="\r")
    for idx, comp_leg in mps.iterrows():
        df.loc[(df.comp_id == comp_leg.comp_id) & (df['timepoint_ms'] > comp_leg.begin_leg_ms)
               & (df['timepoint_ms'] < comp_leg.end_leg_ms),'leg_nr'] = comp_leg.leg_nr
    df = df.dropna(subset=['leg_nr'])
#                 print(mps.head())
#                 print(df.head())

    try:
        print('Uploading positions to db', end="\r")
        df.to_sql('positions', con = engine, index = False, if_exists = 'append', chunksize = 10000)
        print('Added positions of \t{} \t{} \t succesfully to the database'.format(regName, race))
    except IntegrityError as e:
        print('Could not add positions of \t{} \t{} \tto the database because of IntegrityError.'.format(regName,race))
    return df

# Fill columns with extra information to complete database

## Update final rank in race_comp

In [ ]:
cursor.execute("""
UPDATE
    race_comp
SET
    race_comp.rank = (
            SELECT comp_leg.competitor_rank from comp_leg 
                    INNER JOIN legs ON comp_leg.regatta = legs.regatta
                                AND comp_leg.race = legs.race
                                AND comp_leg.leg_nr = legs.leg_nr
            WHERE legs.leg_nr_from_finish = 1
                AND race_comp.regatta = comp_leg.regatta 
                AND race_comp.race = comp_leg.race
                AND race_comp.comp_id = comp_leg.comp_id
)
""")

In [ ]:
cnxn.commit()

## Get chosen side of competitors for leg 1

In [ ]:
for indx, row in eventSelection.iterrows():
    regName = row.regatta
    raceName = row.race

    sql = """SELECT  comp_leg.regatta, comp_leg.race, comp_leg.comp_id
                    ,comp_leg.competitor_started
                    ,comp_leg.competitor_finished
                    ,comp_leg.avg_side

            from comp_leg INNER JOIN regattas
            on regattas.regatta = comp_leg.regatta
            where regattas.regatta = '{}'
                  and leg_nr = 1""".format(regName)
    df = pd.read_sql_query(sql, con = engine)
    for index, row in df.iterrows():
        comp_id = "0x{}".format(row['comp_id'].hex().upper())

        sql = """SELECT  TOP (1) *
          FROM comp_leg
          WHERE regatta = '{}'
          and race = '{}'
          and comp_id = {}
          and leg_nr = 1""".format(regName , raceName , comp_id)
        comp_leg = pd.read_sql_query(sql, con = engine, chunksize=None)

        if not (comp_leg.avg_side.values[0] is None):
#             print(row['regatta'], row['race'] , comp_id , end="\t")
            print('{} {} {} Side already determined'.format(regName, raceName, comp_id))
            continue

        if not row['competitor_started'] or not row['competitor_finished']:
#             print(row['regatta'], row['race'] , comp_id , end="\t")
            print('{} {} {} Competitor did not finish leg'.format(regName, raceName, comp_id))
            continue


        sql = """SELECT  *
          FROM positions
          WHERE regatta = '{}'
          and race = '{}'
          and comp_id = {}
          and leg_nr = 1""".format(regName , raceName, comp_id)
        track = pd.read_sql_query(sql, con = engine, chunksize=None)

        if track.empty:
            print(regName, raceName, comp_id , end="\t")
            print('No track found, try to download it again', end = '\r')
#             uploadPositions(regName, raceName, comp_id)
#             sql = """SELECT  *
#               FROM positions
#               WHERE regatta = '{}'
#               and race = '{}'
#               and comp_id = {}
#               and leg_nr = 1""".format(regName ,raceName, comp_id)
#             track = pd.read_sql_query(sql, con = engine, chunksize=None)
        if track.empty:
            print('No track found {} {} {}'.format(regName, raceName, comp_id)))
            break

        stats = [str(x) for x in trackStatistics(track)]
        cursor.execute("""
        UPDATE comp_leg
        SET    comp_leg.avg_side = {}
               ,comp_leg.most_left = {}
               ,comp_leg.most_right = {}
        WHERE
        regatta = '{}'
          and race = '{}'
          and comp_id = {}
          and leg_nr = 1
          """.format(stats[0], stats[1], stats[2],regName ,raceName , comp_id)
                      )
        cursor.commit()

In [ ]:
cnxn.commit()

## Determining Course Area

In [ ]:
sql = """SELECT  *
  FROM course_areas"""
areas = pd.read_sql_query(sql, con = engine)

areas['equid'] = areas.apply(lambda x:  coordinatesToEquiv(x, centre = False), axis =  1)


for serv in eventSelection:
    for indx, regatta in serv['regattas'].iterrows():
        regName = regatta.regatta
        sql = """SELECT  *
          FROM races
          WHERE races.regatta = '{}'""".format(regName)
        df = pd.read_sql_query(sql, con = engine, index_col=None, coerce_float=True, params=None, parse_dates=None, chunksize=None)

        for ind, race in df.iterrows():
            print('determining racearea of {} {}'.format(regName,race['race'])
                  , end = ' ')
            value = str(getArea(race, areas))
            if value == "-1":
                continue
            print(value)
            cursor.execute("""UPDATE races
                            SET races.course_area_id = {}
                            WHERE regatta = '{}'
                                AND race = '{}'
                            """.format(value, regName, race['race']))
            cursor.commit()

## Number of competitors per race and their relative rank

In [ ]:
cursor.execute("""
                UPDATE
                    races
                SET
                    races.nr_competitors = temp_table.nr_competitors
                FROM
                    (SELECT race_comp.regatta, race_comp.race, count(rank) as nr_competitors
                                              FROM race_comp 
                                              GROUP by regatta, race) AS temp_table
                    INNER JOIN races on temp_table.regatta = races.regatta
                            and temp_table.race = races.race
            """)
cursor.commit()

In [ ]:
cursor.execute("""
                UPDATE
                    comp_leg
                SET
                    comp_leg.rel_rank = temp_table.rel_rank
                FROM
                    (SELECT comp_leg.regatta, comp_leg.race, comp_leg.comp_id
                           ,comp_leg.competitor_rank
                           , comp_leg.competitor_rank/convert(decimal(4,2), races.nr_competitors) as rel_rank
                        FROM comp_leg INNER JOIN races
                            ON comp_leg.regatta = races.regatta 
                            and comp_leg.race = races.race
                        )
                        AS temp_table INNER JOIN comp_leg
                            ON comp_leg.regatta = temp_table.regatta 
                                 and comp_leg.race = temp_table.race
                                 and comp_leg.comp_id = temp_table.comp_id

                """)
cursor.commit()

## Categorize Sailing Style per Race

In [ ]:
regName = 'HWCS 2020 Round 1 - 470 Men'
sql = """SELECT  *
  FROM legs
  WHERE regatta = '{}'
  and leg_nr = 1""".format(regName)
df = pd.read_sql_query(sql, con = engine, index_col=None, coerce_float=True, params=None, parse_dates=None, chunksize=None)
race = df.loc[4,:]
print(race)
sql = """SELECT  *
  FROM sailing_style"""
styles = pd.read_sql_query(sql, con = engine, index_col=None, coerce_float=True, params=None, parse_dates=None, chunksize=None)
style = styles.loc[1,:]
style

In [ ]:


race

In [ ]:
for serv in eventSelection:
    for indx, regatta in serv['regattas'].iterrows():
        print('determining sailing types of {}'.format(regName)
        regName = regatta.regatta
        sql = """SELECT  *
          FROM legs
          WHERE legs.regatta = '{}'
          and leg_nr = 1""".format(regName)
        df = pd.read_sql_query(sql, con = engine, index_col=None, coerce_float=True, params=None, parse_dates=None, chunksize=None)
        
        for ind, race in df.iterrows():
                  , end = ' ')
            print(race.correlation_tacks)
            if isnan(race.correlation_tacks):
                continue
            value = sailing_style(race, styles)
            print(value)
            cursor.execute("""UPDATE races
                            SET races.sail_style_id = {}
                            WHERE regatta = '{}'
                                AND race = '{}'
                            """.format(value, regName, race['race']))
            cursor.commit()

In [ ]:
df

## Positions Start Line

In [ ]:
## get from new positions

In [ ]:
for indx, row in eventSelection.iterrows():    
    regName = row.regatta
    raceName = row.race
    ## Start time
    sql = """SELECT  *
      FROM races
      WHERE regatta = '{}'
      and race = '{}'""".format(regName, raceName)
    race = pd.read_sql_query(sql, con = engine, index_col=None, coerce_float=True,
                             params=None, parse_dates=None, chunksize=None)

    st = race['startOfRace-ms'].values[0] ## start time
    if st is None:
        print('\t No start time found for {} {}'.format(regName, raceName))
        continue


    print('Updating Startline', end = '\r')


    ## position buoys
    sql = """SELECT  *
      FROM courses
      WHERE regatta = '{}'
      and race = '{}'
      and mark_nr = 0""".format(regName, raceName)
    start = pd.read_sql_query(sql, con = engine, index_col=None, coerce_float=True,
                              params=None, parse_dates=None, chunksize=None)

    id_l = start['controlPoint.left.id'].values[0]  #RC
    id_r = start['controlPoint.right.id'].values[0] #Pin

    sql = """SELECT  *
      FROM marks_positions
      WHERE regatta = '{}'
      and race = '{}'
      and (id = {} or id = {})
      and [timepoint-ms] <= {}+3000
      and [timepoint-ms] >= {}-3000""".format(regName, raceName, idToText(id_l), idToText(id_r), st,st)
    st_line = pd.read_sql_query(sql, con = engine)
    #select one timepoint
    if st_line.empty:
        print("\tNo startline available for {} {}".format(regName, raceName))
        continue
    mask = st_line[['id', 'timepoint-ms']].groupby('id').idxmin()['timepoint-ms']
    st_line = st_line.loc[mask].set_index('id')            
    
    if len(st_line)<2:
        print('Startline not complete for {} {}'.format(regName, raceName))
        continue
    rc = st_line.loc[id_l,:]
    pin = st_line.loc[id_r,:]
    st_bearing = bearing(rc,pin)        
        
    ## windmeasurements at start
    skip_wind = 0
    sql = """SELECT * FROM windsources
                    WHERE regatta = '{}'
                        AND race = '{}'
                        AND typeName = 'EXPEDITION'""".format(regName, raceName)
    windsources = pd.read_sql_query(sql, con = engine)
    rc_windsource = windsources.loc[windsources.rc == 1]
    
    if rc_windsource.empty:
         ## wind measurement at RC
        print('Get windsources', end = '\r')
        sql = """SELECT  *
            FROM wind
            WHERE regatta = '{}'
            and race = '{}'
            and [timepoint-ms] <= {}+3000
            and [timepoint-ms] >= {}-3000
            """.format(regName, raceName, st, st)
        wind = pd.read_sql_query(sql, con = engine)
        wind = wind.loc[wind.windSource == 'EXPEDITION']
        if wind.empty:
            print('No wind measurements available for {} {}'.format(regName, raceName))
            skip_wind = 1
        
        else:
            print('Determine closest ws', end = '\r')
            rc = st_line.loc[id_l,:]
            dist = wind[['lat-deg', 'lng-deg']].apply(lambda x: np.linalg.norm([x['lat-deg']- rc['lat-deg'],
                                                                                x['lng-deg']- rc['lng-deg']]),
                                               axis = 1)

            source = wind.loc[dist.idxmin()] 
            ## Update windsources to highlight this source to be at the rc
            sql = """UPDATE windsources
                            SET windsources.rc = 1
                            WHERE regatta = '{}'
                                AND race = '{}'
                                AND typeName = 'EXPEDITION'
                                AND id = '{}'
                            """.format(regName, raceName, source.windSource_id )
            cursor.execute(sql)
            cursor.commit()

    else:
        print('Wind at rc is already determined', end = '\r')
        # So the closest wind source is already known
        sql = """SELECT  *
            FROM wind
            WHERE regatta = '{}'
            and race = '{}'
            and windSource = 'EXPEDITION'
            and windSource_id = '{}'
            """.format(regName, raceName, rc_windsource.id.values[0])
        wind = pd.read_sql_query(sql, con = engine, index_col=None, coerce_float=True, params=None,
                                 parse_dates=None, chunksize=None)
        source = wind.loc[0]
    
    if not skip_wind:
        wind_msr = wind.loc[(wind.windSource_id == source.windSource_id) & (wind['timepoint-ms'] == st)].reset_index()
                    ### check if there always exists one
        if wind_msr.empty:
            wind_msr = wind.loc[(wind.windSource_id == source.windSource_id)].reset_index()
            wind_time = wind_msr['timepoint-ms'].apply(lambda x: abs(x - st)).idxmin()
            wind_msr = wind_msr.loc[wind_time]

        ## determine startline stats
        wind_dir = wind_msr.squeeze()['dampenedTrueBearing-deg']
        dir_diff = wind_dir - (st_bearing - 90) 
        dir_diff = ((dir_diff+ 180)%360) - 180 ## denk na over modulo rekenen, zodat alles tussen -40 + 40 komt

        if dir_diff <-90:
            dir_diff +=180
        if dir_diff >90:
            dir_diff -= 180
        if dir_diff<0:
            side = 'Left'
        else:
            side = 'Right'
#             plt.plot(rc['lng-deg'], rc['lat-deg'], 'r.')
#             plt.plot(pin['lng-deg'], pin['lat-deg'], 'b.')
#             plt.show()
#             print('st_bearing = {}\t perpendicular to st = {}\t windbearing = {}\t calculated angle = {}'.format(st_bearing,
#                                                                                                                 (st_bearing - 90), 
#                                                                                                                 wind_msr.squeeze()['trueBearing-deg'],
#                                                                                                                 dir_diff))
        ## update races table
        sql = """UPDATE races
                        SET races.stl_bearing_diff_wind = {}
                        , races.stl_fav_side = '{}'
                        , races.start_wind_dir = {}
                        , races.stl_bearing = {}
                        WHERE regatta = '{}'
                            AND race = '{}'
                        """.format(dir_diff, side, wind_dir, st_bearing, regName, raceName)
        cursor.execute(sql)
        cursor.commit()

    print('Updating Competitors at Start    ', end = '\r')
    # check whether competitors are already updated
    sql =""" SELECT * from race_comp
                    WHERE regatta = '{}'
                        AND race = '{}'
                        AND pos_startline_abs_x IS NOT NULL                               

                    """.format(regName,
                               raceName)
    df = pd.read_sql(sql, con = engine)
    if not df.empty:
        print('competitor start locations already known for {} {}'.format(regName, raceName))
        continue



    ## positions competitors at start
    sql = """select p.*
            from positions p
            join (select regatta, race, comp_id, min(timepoint_ms) as t
                  from positions
                  group by regatta, race, comp_id) p2
                on p.regatta = p2.regatta and p.race = p2.race and p.comp_id = p2.comp_id 
                and p.timepoint_ms = p2.t
            Inner join comp_leg as cl on 
                    p.regatta = cl.regatta and p.race = cl.race and p.comp_id = cl.comp_id 
                    and p.leg_nr = cl.leg_nr
            where 
            p.regatta = '{}'
            and p.race = '{}'
            and cl.competitor_started = 1 and cl.leg_nr = 1
    """.format(regName, raceName)
    comp = pd.read_sql_query(sql, con = engine, index_col=None, coerce_float=True, params=None,
                             parse_dates=None, chunksize=None)
    if comp.empty:
        print('WARNING: No positions found for competitors')

    X = startline(comp, pin, rc)
    X_x =  np.asarray(X)[0]
    X_y = np.asarray(X)[1]
    plt.plot(X_x, X_y, '.')
    plt.axis('equal')
    plt.show()
    comp['pos_startline_abs_x'] = X_x
    comp['pos_startline_abs_y'] = X_y
    rel_order = X_x.argsort().argsort()/(len(X_x)-1)
    comp['pos_startline_rel'] = rel_order

    ## Update race_comp
    for idx, competitor in comp.iterrows():
        sql = """UPDATE race_comp
                    SET race_comp.pos_startline_abs_x = {}
                    , race_comp.pos_startline_abs_y = {}
                    , race_comp.pos_startline_rel = {}
                    WHERE regatta = '{}'
                        AND race = '{}'
                        AND comp_id = {}
                    """.format(competitor.pos_startline_abs_x,
                               competitor.pos_startline_abs_y,
                               competitor.pos_startline_rel,
                               regName,
                               raceName,
                              idToText(competitor.comp_id))
        cursor.execute(sql)
        cursor.commit()

    print('Succesfully updated startline for {} {}'.format(regName,raceName))

## positions_view

In [ ]:
CREATE VIEW positions_view
WITH SCHEMABINDING
AS 
SELECT
    r.regatta,
    rc.race,
    l.leg_nr,
    c.comp_id,
    timepoint_ms,
    [lat-deg],
	[lng-deg]
	,[speed-kts]
	,[truebearing-deg]
FROM
    dbo.positions p
INNER JOIN dbo.competitors c
    ON c.comp_id = p.comp_id
	 and c.regatta = p.regatta
INNER JOIN dbo.legs l
	ON l.regatta = p.regatta
	 and l.race = p.race
	 and l.leg_nr = p.leg_nr
INNER JOIN dbo.races rc 
    ON rc.regatta = p.regatta
	 and rc.race = p.race
INNER JOIN dbo.regattas r
	ON r.regatta = p.regatta
WHERE l.leg_nr = 1
 and p.timepoint_ms % 20000 = 0
	 ;
        

CREATE NONCLUSTERED INDEX 
    idx_regatta
ON dbo.positions_view(regatta);

## Calculate Correlations

In [ ]:
sql = """
SELECT * from races"""
sql = """
SELECT * from legs 
where pos_startline_abs_x IS NULL and
correlation_side is not null
and leg_nr = 1

"""


eventSelection = pd.read_sql(sql, con= engine)
eventSelection

In [ ]:
## not yet right for other legs then 1, because avg side needs to be calculated first

for idx, row in eventSelection.iterrows():
    stop = 0
    regName = row.regatta
    raceName = row.race
    sql = """
    SELECT * from legs
    where leg_nr = 1
        and regatta = '{}'
        and race = '{}'
        """.format(regName, raceName)

    legs = pd.read_sql(sql, engine)
    for index, row in legs.iterrows():
        
        sql = """
        SELECT comp_leg.*
                , race_comp.pos_startline_abs_x
                , race_comp.pos_startline_abs_y
                ,race_comp.pos_startline_rel 
                    from comp_leg INNER JOIN race_comp
        ON race_comp.regatta = comp_leg.regatta
            and race_comp.race = comp_leg.race
            and race_comp.comp_id = comp_leg.comp_id          
        WHERE comp_leg.regatta = '{}'
        and comp_leg.race = '{}'
        and comp_leg.leg_nr = {}
        """.format( regName,
                    raceName,
                    row['leg_nr'])

        df = pd.read_sql(sql, engine)
        correlations = df.corr()
        try:
            corrs = correlations.rel_rank.replace(np.nan, "NULL", regex=True)  ### replace NaN's by NULL so they can be updated in the sql df

            corrs_side = correlations.avg_side
        except AttributeError as a:
            print('Attribute Error: {} for {} {}'.format(a, regName, raceName))
        try:
            cursor.execute("""
            UPDATE legs
            SET    legs.correlation_tacks = {}
                  ,legs.correlation_side = {}
                  ,legs.correlation_avgSOG = {}
                  ,legs.correlation_traveledDistance = {}
                  ,legs.correlation_jibes = {}
                  ,legs.pos_startline_abs_x = {}
                  ,legs.pos_startline_abs_y = {}
                  ,legs.pos_startline_rel = {}
                  ,legs.cor_side_pos_startline_abs = {}
                  ,legs.cor_side_pos_startline_rel = {}
            WHERE
            regatta = '{}'
            and race = '{}'
            and leg_nr = '{}'
              """.format(corrs['competitor_tacks'],
                         corrs['avg_side'],
                         corrs['competitor_averageSOG-kts'],
                         corrs['competitor_distanceTraveled-m'],
                         corrs['competitor_jibes'], 
                         corrs['pos_startline_abs_x'], 
                         corrs['pos_startline_abs_y'], 
                         corrs['pos_startline_rel'],  
                         corrs_side.pos_startline_abs_x,
                         corrs_side.pos_startline_rel,
                         regName,
                         raceName,
                         row['leg_nr']))        
        except KeyError as e:
            print('Key Error: {} for {} {}'.format(e, regName, raceName))
            stop = 1
        cursor.commit()
        print('{} {} Succesfull'.format(regName, raceName))

In [ ]:
sql = """
SELECT * from legs 
where pos_startline_abs_x IS NULL and
correlation_side is not null
and leg_nr = 1

"""
df = pd.read_sql(sql, con = engine)
df

# Extra

## Usefull other queries

In [ ]:
cursor.execute("""

USE nerinedatabase;
EXEC sp_spaceused;
""")

In [ ]:
cursor.execute("""
DROP INDEX idx ON positions;
CREATE UNIQUE CLUSTERED INDEX idx ON positions (regatta, race, comp_id, timepoint_ms ASC);

""")

In [ ]:
# info over indeces
EXEC sp_helpindex '[[[SCHEMA-NAME.TABLE-NAME]]]'
GO

## snelle manier om aantal rijen in tabel te krijgen
DECLARE @TableName sysname
SET @TableName = 'positions'
 
SELECT OBJECT_NAME(object_id), SUM(row_count) AS rows
FROM sys.dm_db_partition_stats
WHERE object_id = OBJECT_ID(@TableName)
AND index_id < 2
GROUP BY OBJECT_NAME(object_id);

In [ ]:
cursor.commit()

In [ ]:
sql = """SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE'
"""
df = pd.read_sql(sql, con = engine)


# print(df.COLUMN_NAME)
tables = []
for idx,t in df.iterrows():
    sql = """SELECT *
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = N'{}'""".format(t.TABLE_NAME)
    columns = pd.read_sql(sql, con = engine)
    if 'regatta' and 'race' and 'race_id' in columns.COLUMN_NAME.unique():
        tables.append(t.TABLE_NAME)
        
tables.remove('races')

In [ ]:
for t in tables:
    print(t)
    sql = """
    UPDATE {table}
    SET {table}.race_id = (
            SELECT races.race_id from races 
            where races.regatta= {table}.regatta and races.race = {table}.race)
    """.format(table = t)
#     cursor.execute(sql)
#     cursor.commit()
tables

In [ ]:
tables = ['positions']
for t in tables:
    print(t)
    sql = """
    UPDATE {table}
    SET {table}.race_id = (
            SELECT races.race_id from races 
            where races.regatta= {table}.regatta and races.race = {table}.race)
    """.format(table = t)
    cursor.execute(sql)
    cursor.commit()
    print(sql)

In [ ]:
t = 'positions'
    print(t)
    sql = """
    UPDATE {table}
    SET {table}.race_id = (
            SELECT races.race_id from races 
            where races.regatta= {table}.regatta and races.race = {table}.race)
    """.format(table = t)
    cursor.execute(sql)
    cursor.commit(

## move all data to right indexed

In [ ]:

table = 'positions'
for table in tables:
    nt  = table+'2'
    sql = """SELECT * from {}""".format(table)
    df = pd.read_sql(sql, con= engine).drop(columns = ['regatta', 'race'])
    df.to_sql(nt, con= engine, index = None,  if_exists = 'append')
    print(table)

In [10]:
sql = """
SELECT * FROM races

"""
df = pd.read_sql(sql, con = engine)
df
for idx, row in df.iterrows():
    regName = row.regatta
    raceName = row.race
    race_id = idToText(row.race_id)
    print(regName, raceName, end = '\r')
    
    check = """
    SELECT TOP(1) * from positions2
    where leg_nr = 1
    and race_id = {}
    
    """.format(race_id)
    check = pd.read_sql(check, engine)
    if not check.empty:
        continue
    
    sql = """
    SELECT * from positions
    where regatta = '{}'
    and race = '{}'
    """.format(regName, raceName)
    df = pd.read_sql(sql, con= engine).drop(columns = [ 'regatta', 'race'])
    df.race_id = row.race_id
    condition = 'race_id = {} '.format(race_id)
    toSql(df, 'positions2', engine, regName, raceName, condition)

Succesfully uploaded positions2 for regatta: 	HWCS 2020 Round 1 - Finn, race: 	M Medal (FINN)
Succesfully uploaded positions2 for regatta: 	HWCS 2020 Round 1 - Laser, race: 	M Medal (Laser Standard)
Succesfully uploaded positions2 for regatta: 	HWCS 2020 Round 1 - Laser Radial, race: 	M Medal (Laser Radial)

OperationalError: (pyodbc.OperationalError) ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: De externe host heeft een verbinding verbroken.\r\n (10054) (SQLExecute); [08S01] [Microsoft][ODBC Driver 17 for SQL Server]Communication link failure (10054)')
[SQL: INSERT INTO positions2 (leg_nr, comp_id, timepoint_ms, [lat-deg], [lng-deg], [speed-kts], [truebearing-deg], [calculated_windSpd], [calculated_windDir], race_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ((1, b'\x00?_\x90B)O\x8d\xbdnQ8\xf5\x98\x1b\\', 1567142041000, 35.26231, 139.519535, 5.72, 161.99, None, None, b'\xa2\x95\x9c\x80\xac\xdd\x017\xfc\xdf\x06w?\x91rv'), (1, b'\x00?_\x90B)O\x8d\xbdnQ8\xf5\x98\x1b\\', 1567142042000, 35.262286, 139.519542, 5.28, 164.99, None, None, b'\xa2\x95\x9c\x80\xac\xdd\x017\xfc\xdf\x06w?\x91rv'), (1, b'\x00?_\x90B)O\x8d\xbdnQ8\xf5\x98\x1b\\', 1567142043000, 35.262267, 139.519551, 4.04, 160.99, None, None, b'\xa2\x95\x9c\x80\xac\xdd\x017\xfc\xdf\x06w?\x91rv'), (1, b'\x00?_\x90B)O\x8d\xbdnQ8\xf5\x98\x1b\\', 1567142044000, 35.262247, 139.519558, 4.47, 163.99, None, None, b'\xa2\x95\x9c\x80\xac\xdd\x017\xfc\xdf\x06w?\x91rv'), (1, b'\x00?_\x90B)O\x8d\xbdnQ8\xf5\x98\x1b\\', 1567142045000, 35.262225, 139.519561, 5.17, 174.99, None, None, b'\xa2\x95\x9c\x80\xac\xdd\x017\xfc\xdf\x06w?\x91rv'), (1, b'\x00?_\x90B)O\x8d\xbdnQ8\xf5\x98\x1b\\', 1567142046000, 35.262205, 139.519568, 4.36, 165.99, None, None, b'\xa2\x95\x9c\x80\xac\xdd\x017\xfc\xdf\x06w?\x91rv'), (1, b'\x00?_\x90B)O\x8d\xbdnQ8\xf5\x98\x1b\\', 1567142047000, 35.262186, 139.519578, 4.04, 158.99, None, None, b'\xa2\x95\x9c\x80\xac\xdd\x017\xfc\xdf\x06w?\x91rv'), (1, b'\x00?_\x90B)O\x8d\xbdnQ8\xf5\x98\x1b\\', 1567142048000, 35.262165, 139.519582, 5.13, 169.99, None, None, b'\xa2\x95\x9c\x80\xac\xdd\x017\xfc\xdf\x06w?\x91rv')  ... displaying 10 of 174893 total bound parameter sets ...  (6, b'\xffx\xcf\xf5^vE\xd7\xadz:\x86\xcdG\xb3\xfa', 1567145658000, 35.260085, 139.533329, 10.68, 320.0, None, None, b'\xa2\x95\x9c\x80\xac\xdd\x017\xfc\xdf\x06w?\x91rv'), (6, b'\xffx\xcf\xf5^vE\xd7\xadz:\x86\xcdG\xb3\xfa', 1567145659000, 35.260123, 139.533292, 10.3, 321.0, None, None, b'\xa2\x95\x9c\x80\xac\xdd\x017\xfc\xdf\x06w?\x91rv'))]
(Background on this error at: http://sqlalche.me/e/e3q8)

In [9]:
sql = """
SELECT * FROM races

"""
df = pd.read_sql(sql, con = engine)
df
for idx, row in df.iterrows():
    regName = row.regatta
    raceName = row.race
    race_id = idToText(row.race_id)
    print(regName, raceName, end = '\r')
    
    sql = """
    SELECT * from windsources2
    WHERE race_id = {}
    and rc = 1
    """.format(race_id)
    rc = pd.read_sql(sql, engine)
    if rc.empty:
        print('rc is empty {} {}'.format(regName,raceName))
        continue
    rc = rc.iloc[0]
    
    check = """
    SELECT TOP(1) * from wind2
    where race_id = {}
    and windSource = '{}'
    and windSource_id = '{}'
    """.format(race_id, rc.typeName, rc.id)
    check = pd.read_sql(check, engine)
    if not check.empty:
        continue
    
    sql = """
    SELECT * from wind
    where regatta = '{}'
    and race ='{}'
    and windSource = '{}'
    and windSource_id = '{}'
    """.format(regName, raceName, rc.typeName, rc.id)
    df = pd.read_sql(sql, con= engine).drop(columns = [ 'regatta', 'race'])
    df['race_id'] = row.race_id
    
    condition = "race_id = {} and windSource = '{}' and windSource_id = '{}'".format(race_id, rc.typeName, rc.id)
    toSql(df, 'wind2', engine, regName, raceName, condition)

rc is empty HWCS 2020 Round 1 - 470 Men R1 (470 Men)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - 49er, race: 	M Medal (49ER)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - 49er, race: 	R1 (49ER)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - 49er, race: 	R2 (49ER)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - 49er, race: 	R3 (49ER)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - 49er, race: 	R4 (49ER)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - 49er, race: 	R5  (49ER)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - 49er, race: 	R6 (49ER)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - 49er, race: 	R7 (49ER)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - 49erFX, race: 	M Medal (49FX)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - 49erFX, race: 	R1(49FX)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - 49erFX, race: 	R2(49FX)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - 49erFX, race: 	R3 (49FX)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - 49erFX, race: 	R4 (49FX)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - 49erFX, race: 	R5 (49FX)
rc is empty HWCS 2020 Round 1 - Finn M Medal (FINN)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Finn, race: 	R08 (FINN)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Finn, race: 	R09 (FINN)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Finn, race: 	R1 (FINN)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Finn, race: 	R10 (FINN)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Finn, race: 	R2 (FINN)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Finn, race: 	R3 (FINN)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Finn, race: 	R4 (FINN)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Finn, race: 	R5 (FINN)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Finn, race: 	R6 (FINN)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Finn, race: 	R7 (FINN)
rc is empty HWCS 2020 Round 1 - Laser M Medal (Laser Standard)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser, race: 	R08 (Laser Standard)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser, race: 	R09 (Laser Standard)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser, race: 	R1 (Laser Standard)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser, race: 	R10 (Laser Standard)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser, race: 	R2 (Laser Standard)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser, race: 	R3 (Laser Standard)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser, race: 	R4 (Laser Standard)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser, race: 	R5 (Laser Standard)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser, race: 	R6 (Laser Standard)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser, race: 	R7 (Laser Standard)
rc is empty HWCS 2020 Round 1 - Laser Radial M Medal (Laser Radial)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser Radial, race: 	R08 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser Radial, race: 	R09 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser Radial, race: 	R1 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser Radial, race: 	R10 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser Radial, race: 	R2 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser Radial, race: 	R3 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser Radial, race: 	R4 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser Radial, race: 	R5 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser Radial, race: 	R6 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Laser Radial, race: 	R7 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Nacra 17, race: 	M Medal (Nacra 17)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Nacra 17, race: 	R1 (Nacra 17)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Nacra 17, race: 	R2 (Nacra 17)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Nacra 17, race: 	R3 (Nacra 17)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Nacra 17, race: 	R4 (Nacra 17)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - Nacra 17, race: 	R5 (Nacra 17)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Men, race: 	M Medal (RSX Men)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Men, race: 	R1 (RSX Men)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Men, race: 	R10 (RSX Men)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Men, race: 	R11 (RSX Men)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Men, race: 	R12 (RSX Men)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Men, race: 	R2 (RSX Men)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Men, race: 	R3 (RSX Men)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Men, race: 	R4 (RSX Men)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Men, race: 	R5 (RSX Men)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Men, race: 	R6 (RSX Men)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Men, race: 	R7 (RSX Men)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Men, race: 	R8 (RSX Men)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Men, race: 	R9 (RSX Men)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Women, race: 	M Medal (RSX Women)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Women, race: 	R1 (RSX Women)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Women, race: 	R10 (RSX Women)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Women, race: 	R2 (RSX Women)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Women, race: 	R3 (RSX Women)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Women, race: 	R4 (RSX Women)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Women, race: 	R5 (RSX Women)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Women, race: 	R6 (RSX Women)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Women, race: 	R7 (RSX Women)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Women, race: 	R8 (RSX Women)
Succesfully uploaded wind2 for regatta: 	HWCS 2020 Round 1 - RS:X Women, race: 	R9 (RSX Women)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 470 Men, race: 	R1 (470 Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 470 Men, race: 	R10 (470 Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 470 Men, race: 	R2 (470 Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 470 Men, race: 	R3 (470 Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 470 Men, race: 	R4 (470 Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 470 Men, race: 	R5 (470 Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 470 Men, race: 	R6 (470 Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 470 Men, race: 	R7 (470 Men)
rc is empty Tokyo 2019 - 470 Men R8 (470 Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 470 Men, race: 	R9 (470 Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er, race: 	R1 (49er)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er, race: 	R10 (49er)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er, race: 	R11 (49er)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er, race: 	R12 (49er)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er, race: 	R13 Medal (49er)

Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er, race: 	R2 (49er)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er, race: 	R3 (49er)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er, race: 	R4 (49er)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er, race: 	R5 (49er)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er, race: 	R6 (49er)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er, race: 	R7 (49er)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er, race: 	R8 (49er)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er, race: 	R9 (49er)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er FX, race: 	R1 (49erFX)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er FX, race: 	R10 (49erFX)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er FX, race: 	R11 (49erFX)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er FX, race: 	R12 (49erFX)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er FX, race: 	R13 Medal (49erFX)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er FX, race: 	R2 (49erFX)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er FX, race: 	R3 (49erFX)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er FX, race: 	R4 (49erFX)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er FX, race: 	R5 (49erFX)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er FX, race: 	R6 (49erFX)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er FX, race: 	R7 (49erFX)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er FX, race: 	R8 (49erFX)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - 49er FX, race: 	R9 (49erFX)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Finn, race: 	R1 (Finn)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Finn, race: 	R10 (Finn)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Finn, race: 	R2 (Finn)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Finn, race: 	R3 (Finn)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Finn, race: 	R4 (Finn)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Finn, race: 	R5 (Finn)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Finn, race: 	R6 (Finn)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Finn, race: 	R7 (Finn)
rc is empty Tokyo 2019 - Finn R8 (Finn)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Finn, race: 	R9 (Finn)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Laser, race: 	R1 (Laser Int.)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Laser, race: 	R10 (Laser Int.)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Laser, race: 	R2 (Laser Int.)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Laser, race: 	R3 (Laser Int.)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Laser, race: 	R4 (Laser Int.)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Laser, race: 	R5 (Laser Int.)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Laser, race: 	R6 (Laser Int.)
rc is empty Tokyo 2019 - Laser R7 (Laser Int.)
rc is empty Tokyo 2019 - Laser R8 (Laser Int.)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Laser, race: 	R9 (Laser Int.)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Laser Radial, race: 	R1 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Laser Radial, race: 	R10 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Laser Radial, race: 	R2 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Laser Radial, race: 	R3 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Laser Radial, race: 	R4 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Laser Radial, race: 	R5 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Laser Radial, race: 	R6 (Laser Radial)
rc is empty Tokyo 2019 - Laser Radial R7 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Laser Radial, race: 	R8 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Laser Radial, race: 	R9 (Laser Radial)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Nacra 17, race: 	R1 (Nacra 17)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Nacra 17, race: 	R10 (Nacra 17)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Nacra 17, race: 	R11 (Nacra 17)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Nacra 17, race: 	R12 (Nacra 17)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Nacra 17, race: 	R13 Medal (Nacra 17)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Nacra 17, race: 	R2 (Nacra 17)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Nacra 17, race: 	R3 (Nacra 17)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Nacra 17, race: 	R4 (Nacra 17)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Nacra 17, race: 	R5 (Nacra 17)
rc is empty Tokyo 2019 - Nacra 17 R6 (Nacra 17)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Nacra 17, race: 	R7 (Nacra 17)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Nacra 17, race: 	R8 (Nacra 17)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - Nacra 17, race: 	R9 (Nacra 17)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Men, race: 	R1 (RS:X Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Men, race: 	R10 (RS:X Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Men, race: 	R11 Medal (RS:X Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Men, race: 	R2 (RS:X men)
rc is empty Tokyo 2019 - RS:X Men R3 (RS:X Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Men, race: 	R4 (RS:X Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Men, race: 	R5 (RS:X Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Men, race: 	R6 (RS:X Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Men, race: 	R7 (RS:X Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Men, race: 	R8 (RS:X Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Men, race: 	R9 (RS:X Men)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Women, race: 	R1 (RS:X Women)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Women, race: 	R10 (RS:X Women)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Women, race: 	R11 (RS:X Women)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Women, race: 	R12 Medal (RS:X Women)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Women, race: 	R2 (RS:X Women)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Women, race: 	R3 (RS:X Women)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Women, race: 	R4 (RS:X Women)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Women, race: 	R5 (RS:X Women)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Women, race: 	R6 (RS:X Women)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Women, race: 	R7 (RS:X Women)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Women, race: 	R8 (RS:X Women)
Succesfully uploaded wind2 for regatta: 	Tokyo 2019 - RS:X Women, race: 	R9 (RS:X Women)
Succesfully uploaded wind2 for regatta: 	Toyko 2019 - 470 Women, race: 	R1 (470 Women)
Succesfully uploaded wind2 for regatta: 	Toyko 2019 - 470 Women, race: 	R10 (470 Women)
Succesfully uploaded wind2 for regatta: 	Toyko 2019 - 470 Women, race: 	R11 Medal (470 Women)
Succesfully uploaded wind2 for regatta: 	Toyko 2019 - 470 Women, race: 	R2 (470 Women)
rc is empty Toyko 2019 - 470 Women R3 (470 Women)
Succesfully uploaded wind2 for regatta: 	Toyko 2019 - 470 Women, race: 	R4 (470 Women)
Succesfully uploaded wind2 for regatta: 	Toyko 2019 - 470 Women, race: 	R5 (470 Women)
Succesfully uploaded wind2 for regatta: 	Toyko 2019 - 470 Women, race: 	R6 (470 Women)
Succesfully uploaded wind2 for regatta: 	Toyko 2019 - 470 Women, race: 	R7 (470 Women)
Succesfully uploaded wind2 for regatta: 	Toyko 2019 - 470 Women, race: 	R8 (470 Women)
Succesfully uploaded wind2 for regatta: 	Toyko 2019 - 470 Women, race: 	R9 (470 Women)
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 470 Men, race: 	R1

Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 470 Men, race: 	R2
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 470 Men, race: 	R3
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 470 Men, race: 	R4
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 470 Men, race: 	R5
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 470 Men, race: 	R6
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 470 Men, race: 	R7
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 470 Men, race: 	R8
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 470 Women, race: 	R1
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 470 Women, race: 	R2
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 470 Women, race: 	R3
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 470 Women, race: 	R4
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 470 Women, race: 	R5
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 470 Women, race: 	R6
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 470 Women, race: 	R7
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 470 Women, race: 	R8
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49er, race: 	M Medal (49er)
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49er, race: 	R1
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49er, race: 	R2
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49er, race: 	R3
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49er, race: 	R4
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49er, race: 	R5
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49er, race: 	R6
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49er, race: 	R7
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49er, race: 	R8
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49er, race: 	R9
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49erFX, race: 	M Medal (49erFX)
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49erFX, race: 	R1
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49erFX, race: 	R2
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49erFX, race: 	R3
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49erFX, race: 	R4
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49erFX, race: 	R5
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49erFX, race: 	R6
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - 49erFX, race: 	R7
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Finn, race: 	R1
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Finn, race: 	R2
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Finn, race: 	R3
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Finn, race: 	R4
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Finn, race: 	R5
rc is empty WCS 2019 Enoshima - Finn R6
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Finn, race: 	R7
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Finn, race: 	R8
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Finn, race: 	R9
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Laser, race: 	M Medal (Laser)
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Laser, race: 	R1
rc is empty WCS 2019 Enoshima - Laser R2
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Laser, race: 	R3
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Laser, race: 	R4
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Laser, race: 	R5
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Laser, race: 	R6
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Laser, race: 	R7
rc is empty WCS 2019 Enoshima - Laser R8
rc is empty WCS 2019 Enoshima - Laser R9
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Laser Radial, race: 	M Medal (Laser Radial)
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Laser Radial, race: 	R1
rc is empty WCS 2019 Enoshima - Laser Radial R2
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Laser Radial, race: 	R3
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Laser Radial, race: 	R4
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Laser Radial, race: 	R5
rc is empty WCS 2019 Enoshima - Laser Radial R6
rc is empty WCS 2019 Enoshima - Laser Radial R7
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Nacra 17, race: 	M Medal (Nacra 17)
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Nacra 17, race: 	R1
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Nacra 17, race: 	R2
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Nacra 17, race: 	R3
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Nacra 17, race: 	R4
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Nacra 17, race: 	R5
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Nacra 17, race: 	R6
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Nacra 17, race: 	R7
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Nacra 17, race: 	R8
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - Nacra 17, race: 	R9
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Men, race: 	M Medal (RS:X Men)
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Men, race: 	R1
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Men, race: 	R2
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Men, race: 	R3
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Men, race: 	R4
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Men, race: 	R5
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Men, race: 	R6
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Men, race: 	R7
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Men, race: 	R8
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Women, race: 	M Medal (RS:X Women)
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Women, race: 	R1
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Women, race: 	R2
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Women, race: 	R3
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Women, race: 	R4
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Women, race: 	R5
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Women, race: 	R6
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Women, race: 	R7
Succesfully uploaded wind2 for regatta: 	WCS 2019 Enoshima - RS:X Women, race: 	R8

In [18]:
rc.iloc[0].empty

False